### ISSUE TITLE
Danish voice from Danish Parliament

### ISSUE THREAD

**Issue by ole-tange** [MultiVocal/MultiVocal-roskilde#1]
I could not find your email address, so here is an issue :)

We talked at Driving IT about getting access to recordings from the Danish Parliament.

I have now looked into the matter: The license currently is CC-By-ND. If that is not acceptable then let me know what license we should try to change this into.

By rough guesstimate there should be around 5000 hours of high quality speech and transcription with timestamps whenever the speaker changes.

Scrapingwise it also looks doable: The videos are compatible with youtube-dl, so this will probably download all videos from the parliament hall:

parallel youtube-dl http://mobiltv.ft.dk/video/20{1}1/salen/{2} ::: {10..17} ::: {1..120}

In the HTML of http://www.ft.dk/aktuelt/webtv/video/20101/salen/17.aspx?as=1#pv I find:
  `<a class="sharelink icon-ft_del" title="Del denne tale" href='javascript:oShare("Tale af  Christine Antorini (S)","2010-11-12T10:07:56","2010-11-12T10:08:44", 1)'></a>`
 
which seems to be the from-to-timestamps for “Christine Antorini”s speech.

Contact me at ota@prosa.dk if you want to discuss this more.

**Comment by faaip** [comment]
Hi Ole.

Thank you for your message and sorry for getting back to you late. I'm afraid this is right now out of scope, since we are still working on our physical installation and voice building. I will get back to you if it's becomes more feasible :) Enjoy nytår and thank you for getting in touch!
